version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - default_network
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka:
    build: .
    networks:
      - default_network
    ports:
      - "9092"
    environment:
      DOCKER_API_VERSION: 1.22
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "TopicCurrency:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

networks:
  default_network:
    name: default_network